title: Open Banking UK Public APIs
description: This is a single toolbox for working with the public resources available as part of the UK Open Banking. These are all of the resources that do not require authentication, and are using the common UK Open Banking API format.
image: https://postman-toolboxes.s3.amazonaws.com/assets/uk-banking/open-banking-uk.png
url: https://postman-toolboxes.github.io/open-banking-uk-public
email: info@postman.com

github_user: postman-toolboxes
github_repo: open-banking-uk-public
github_branch: master

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'kin.lane@postman.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
